[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center","--transition-step", "30", "--transition-fps", "60"]
set = false
[config]
# ...

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar/colors.css'
output_path = '~/.config/waybar/colors-matu.css'
post_hook = 'pkill -SIGUSR2 waybar'
[templates.vencord]
input_path = '~/.config/matugen/templates/vencord/midnight-discord.css'
output_path = '~/.config/Vencord/themes/midnight-discord.css'
[templates.mako]
input_path = '~/.config/matugen/templates/mako/mako.txt'
output_path = '~/.config/mako/mako-colors'
post_hook = 'makoctl reload'
[templates.kitty]
input_path = '~/.config/matugen/templates/kitty/kitty-colors.conf'
output_path = '~/.config/kitty/colors-kitty.conf'
post_hook = 'pkill -SIGUSR1 kitty'
[templates.rofi]
input_path = '~/.config/matugen/templates/rofi/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'
[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'
post_hook = 'nautilus -q && nautilus &'
[templates.qt5ct]
input_path = '~/.config/matugen/templates/qt5ct/colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'
[templates.kvantum]
input_path = '~/.config/matugen/templates/kvantum/kvantum.svg'
output_path = '~/.config/Kvantum/matugen/matugen.svg'

[templates.kvantum-config]
input_path = '~/.config/matugen/templates/kvantum/matugen.kvconfig'
output_path = '~/.config/Kvantum/matugen/matugen.kvconfig'
post_hook = 'kvantummanager --set matugen'
[templates.qt6ct]
input_path = '~/.config/matugen/templates/qt5ct/colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'
[templates.hyprland]
input_path = '~/.config/matugen/templates/hypr/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'
[templates.btop]
input_path = '~/.config/matugen/templates/btop/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
[templates.cava]
input_path = '~/.config/matugen/templates/cava/cava-colors.ini'
output_path = '~/.config/cava/themes/your-theme'
post_hook = "pkill -USR1 cava"
[templates.neovim]
input_path = '~/.config/matugen/templates/neovim/colors.lua'
output_path = '~/.config/nvim/lua/colors/matugen.lua'
